//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Step_v0.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Step_v0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 427 express 315 kph Moscow-Ostana
        ///428 conventional 50 kph Moscow-Sochi
        ///429 express 300 kph Vladimir-Tver
        ///
        ///.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Ostanovki_list&gt;
        ///  &lt;ostanovka name =&quot;Москва&quot;&gt;
        ///    &lt;info&gt;50 48&lt;/info&gt;
        ///  &lt;/ostanovka&gt;
        ///  &lt;ostanovka name =&quot;Нижние-Котлы&quot;&gt;
        ///    &lt;info&gt;107 48&lt;/info&gt;
        ///  &lt;/ostanovka&gt;
        ///  &lt;ostanovka name =&quot;Коломенская&quot;&gt;
        ///    &lt;info&gt;177 48&lt;/info&gt;
        ///  &lt;/ostanovka&gt;
        ///  &lt;ostanovka name =&quot;Расторгуево&quot;&gt;
        ///    &lt;info&gt;244 48&lt;/info&gt;
        ///  &lt;/ostanovka&gt;
        ///  &lt;ostanovka name =&quot;Взлетная&quot;&gt;
        ///    &lt;info&gt;337 48&lt;/info&gt;
        ///  &lt;/ostanovka&gt;
        ///  &lt;ostanovka name =&quot;Барыбино&quot;&gt;
        ///    &lt;info&gt;420 48&lt;/info&gt;
        ///  &lt;/ostanovka&gt;
        ///  &lt;ostanovka name =&quot;Кашира&quot;&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ostanovki {
            get {
                return ResourceManager.GetString("Ostanovki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Passander_list&gt;
        ///  &lt;passagir&gt;
        ///    &lt;info&gt;Samatov Sergey 428 20 2 A&lt;/info&gt;
        ///  &lt;/passagir&gt;
        ///  &lt;passagir&gt;
        ///    &lt;info&gt;Salatov Ivan 427 18 1 A&lt;/info&gt;
        ///  &lt;/passagir&gt;
        ///  &lt;passagir&gt;
        ///    &lt;info&gt;Saratov Anton 427 1 4 C&lt;/info&gt;
        ///  &lt;/passagir&gt;
        ///  &lt;passagir&gt;
        ///    &lt;info&gt;Safatov Oleg 429 4 5 D&lt;/info&gt;
        ///  &lt;/passagir&gt;
        ///  &lt;passagir&gt;
        ///    &lt;info&gt;Saratov Maksim 428 4 3 B&lt;/info&gt;
        ///  &lt;/passagir&gt;
        ///&lt;/Passander_list&gt;.
        /// </summary>
        internal static string Passanger {
            get {
                return ResourceManager.GetString("Passanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Train_list&gt;
        ///  &lt;train name =&quot;427&quot;&gt;
        ///    &lt;type&gt;
        ///      express
        ///    &lt;/type&gt;  
        ///&lt;distanation&gt;Москва Нижние-Котлы Расторгуево Барыбино Кашира Яганово Узуново Тула&lt;/distanation&gt;
        ///&lt;time&gt;08:00 08:23 08:50 09:20 11:45 13:30 14:15 16:00&lt;/time&gt;
        ///  &lt;/train&gt;
        ///  &lt;train name =&quot;428&quot;&gt;
        ///    &lt;type&gt;
        ///      express
        ///    &lt;/type&gt;
        ///&lt;distanation&gt;Москва Нижние-Котлы Расторгуево Барыбино Кашира Яганово Узуново&lt;/distanation&gt;
        ///    &lt;time&gt;08:00 09:23 10:50 11:20 13:45 15:30 16:15&lt;/time&gt;
        ///  &lt;/train&gt;
        ///  &lt;train  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Poezd {
            get {
                return ResourceManager.GetString("Poezd", resourceCulture);
            }
        }
    }
}
